name: "Continuous integration"

on:
  on:
    - push
    - pull_request

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      # install npm dependencies
      - run: yarn install --frozen-lockfile
      - run: yarn test
      - run: yarn build
